"""运行时事件与 actor 的封闭枚举。"""

from enum import StrEnum


MAX_EVENT_PAYLOAD_BYTES = 64 * 1024


class ActorType(StrEnum):
    USER = "USER"
    MODULE = "MODULE"
    ROLE = "ROLE"
    ORCHESTRATOR = "ORCHESTRATOR"
    WORKER = "WORKER"
    TOOL = "TOOL"
    SYSTEM = "SYSTEM"


class EventType(StrEnum):
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_RESUMED = "SESSION_RESUMED"
    SESSION_PAUSED = "SESSION_PAUSED"
    SESSION_COMPLETED = "SESSION_COMPLETED"
    SESSION_FAILED = "SESSION_FAILED"
    PROJECT_ROOT_REBOUND = "PROJECT_ROOT_REBOUND"
    USER_INPUT_RECORDED = "USER_INPUT_RECORDED"
    ROLE_SELECTED = "ROLE_SELECTED"
    ROLE_STARTED = "ROLE_STARTED"
    ROLE_COMPLETED = "ROLE_COMPLETED"
    ROLE_FAILED = "ROLE_FAILED"
    CONTEXT_BUILD_STARTED = "CONTEXT_BUILD_STARTED"
    CONTEXT_BUILD_COMPLETED = "CONTEXT_BUILD_COMPLETED"
    TOOL_CALL_REQUESTED = "TOOL_CALL_REQUESTED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    TOOL_CALL_TIMED_OUT = "TOOL_CALL_TIMED_OUT"
    ARTIFACT_STAGED = "ARTIFACT_STAGED"
    ARTIFACT_COMMITTED = "ARTIFACT_COMMITTED"
    PROJECT_STATE_READ = "PROJECT_STATE_READ"
    PROJECT_STATE_COMMIT_REQUESTED = "PROJECT_STATE_COMMIT_REQUESTED"
    PROJECT_STATE_COMMITTED = "PROJECT_STATE_COMMITTED"
    PROJECT_STATE_CONFLICT = "PROJECT_STATE_CONFLICT"
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    LEASE_ACQUIRED = "LEASE_ACQUIRED"
    LEASE_RENEWED = "LEASE_RENEWED"
    LEASE_RELEASED = "LEASE_RELEASED"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    USER_APPROVAL_REQUIRED = "USER_APPROVAL_REQUIRED"
    USER_APPROVAL_RECORDED = "USER_APPROVAL_RECORDED"
