"""F13.1 正式 Deterministic Context Builder。"""

from .builder import ContextBuilder, build_context, resume_context
from .models import (
    ContextBuildRequest,
    ContextOmittedSource,
    ContextPackage,
    ContextResumePackage,
    ContextSource,
    ContextSourceDelta,
)
from .semantic import (
    CONTEXT_CLASSES,
    DEPENDENCY_ROOT_NAMES,
    ContextSemanticBuilder,
    ContextSemanticModel,
    ContextUnit,
)
from .shadow import (
    COVERAGE_STATES,
    ShadowClassification,
    ShadowClassifier,
    ShadowComparison,
    ShadowComparisonBuilder,
    ShadowCoverageGate,
    ShadowGateResult,
)
from .enforced import EnforcementDecision, EnforcedCoverageGate
from .selective import (
    SelectiveCandidateEvaluation,
    SelectiveContextBuilder,
    SelectiveContextEvaluator,
)
from .architecture import ShadowFirstContextRuntime, ShadowFirstEvaluation
from .escalation import (
    ContextAuthorization,
    ContextEscalationRuntime,
    ContextExpansion,
    ContextRecovery,
    ContextRequest,
    ExpansionLoopResult,
    ExpandedSource,
)
from .incremental import (
    REUSE_STATUSES,
    ContextDelta,
    DependencyAwareInvalidator,
    IncrementalContextBuilder,
    IncrementalContextManifest,
    IncrementalContextUnit,
    compare_mandatory_context,
)
from .summary import (
    AUTHORITY_LEVELS,
    SUMMARY_TYPES,
    CanonicalSummary,
    CanonicalSummaryCache,
    DeterministicSummaryBuilder,
    SemanticSummaryShadowBuilder,
    SummarySource,
    assert_summary_usable,
    validate_summary_sources,
)
from .policy import ContextBudgetConfig, ContextPolicy, ContextSourceRule
from .rollover import (
    ContextRolloverService,
    FreshInvocationContext,
    InvocationStats,
    RolloverDecision,
    RolloverHandoff,
    RolloverPolicy,
    evaluate_rollover,
    evaluate_adaptive_rollover,
    load_rollover_policy,
)

__all__ = [
    "ContextBuildRequest",
    "ContextBuilder",
    "ContextBudgetConfig",
    "ContextOmittedSource",
    "ContextPackage",
    "ContextPolicy",
    "ContextResumePackage",
    "ContextSource",
    "ContextSourceDelta",
    "CONTEXT_CLASSES",
    "DEPENDENCY_ROOT_NAMES",
    "ContextSemanticBuilder",
    "ContextSemanticModel",
    "ContextUnit",
    "COVERAGE_STATES",
    "ShadowClassification",
    "ShadowClassifier",
    "ShadowComparison",
    "ShadowComparisonBuilder",
    "ShadowCoverageGate",
    "ShadowGateResult",
    "EnforcementDecision",
    "EnforcedCoverageGate",
    "SelectiveCandidateEvaluation",
    "SelectiveContextBuilder",
    "SelectiveContextEvaluator",
    "ShadowFirstContextRuntime",
    "ShadowFirstEvaluation",
    "ContextAuthorization",
    "ContextEscalationRuntime",
    "ContextExpansion",
    "ContextRecovery",
    "ContextRequest",
    "ExpansionLoopResult",
    "ExpandedSource",
    "REUSE_STATUSES",
    "ContextDelta",
    "DependencyAwareInvalidator",
    "IncrementalContextBuilder",
    "IncrementalContextManifest",
    "IncrementalContextUnit",
    "compare_mandatory_context",
    "AUTHORITY_LEVELS",
    "SUMMARY_TYPES",
    "CanonicalSummary",
    "CanonicalSummaryCache",
    "DeterministicSummaryBuilder",
    "SemanticSummaryShadowBuilder",
    "SummarySource",
    "assert_summary_usable",
    "validate_summary_sources",
    "ContextSourceRule",
    "ContextRolloverService",
    "FreshInvocationContext",
    "InvocationStats",
    "RolloverDecision",
    "RolloverHandoff",
    "RolloverPolicy",
    "build_context",
    "evaluate_rollover",
    "evaluate_adaptive_rollover",
    "load_rollover_policy",
    "resume_context",
]
